name: Update GitHub Profile

on:
  workflow_dispatch:

  schedule:
    - cron: "0 15 * * *"

permissions:
  contents: write

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false

      - name: Generate profile
        run: npm run generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md

          if git diff --cached --quiet; then
            echo "No profile changes"
          else
            git commit -m "Update GitHub profile"
            git push
          fi
